<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRUKYbcx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRUKYbcx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRUKYbcx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRUKYbcx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRUKYbcx\App_KernelDevDebugContainer([
    'container.build_hash' => 'RUKYbcx',
    'container.build_id' => '652c4480',
    'container.build_time' => 1681066802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRUKYbcx');
